JobBoard.UI/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.DataLayer;
using Microsoft.AspNet.Identity;

namespace JobBoard.UI.Controllers
{
    [Authorize(Roles ="Admin, Managers")]
    public class ApplicationsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Applications
        public ActionResult Index()
        {
            var applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail);
            string userID = User.Identity.GetUserId();


            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                applications = from x in applications
                               where x.OpenPosition.Location.ManagerID == userID
                               select x;

            }
            return View(applications.ToList());
        }

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }


        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            string userID = User.Identity.GetUserId();
            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                if (userID!=application.OpenPosition.Location.ManagerID)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

            }
            ViewBag.ApplicationStatusID = new SelectList(db.ApplicationStatus1, "ApplicationStatusID", "StatusName", application.ApplicationStatusID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", application.UserID);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,ApplicationStatusID,ResumeFileName")] Application application)
        {
            if (ModelState.IsValid)
            {
                // we don't want the users to be able to edit all of the fields so we have to got back and get those read only fields
                // geting two instances of the same object from the same instnce of JobBoardEntities cause errors so we create a  secound JobBoardEntities
                using (JobBoardEntities db2 = new JobBoardEntities())
                {



                    Application oldApplication = (from x in db2.Applications
                                                  where x.ApplicationID == application.ApplicationID
                                                  select x).Single();
                    application.ApplicationDate = oldApplication.ApplicationDate;
                    application.OpenPositionID = oldApplication.OpenPositionID;
                    application.UserID = oldApplication.UserID;
                    application.ResumeFileName = oldApplication.ResumeFileName;

                    string userID = User.Identity.GetUserId();
                    if (!User.IsInRole("Admin"))
                    {
                        // the user is not an admin
                        if (userID != oldApplication.OpenPosition.Location.ManagerID)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                        }

                    }
                }
                db.Entry(application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationStatusID = new SelectList(db.ApplicationStatus1, "ApplicationStatusID", "StatusName", application.ApplicationStatusID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", application.UserID);
            return View(application);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            string userID = User.Identity.GetUserId();
            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                if (userID != application.OpenPosition.Location.ManagerID)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = db.Applications.Find(id);
            string userID = User.Identity.GetUserId();
            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                if (userID != application.OpenPosition.Location.ManagerID)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

            }
            db.Applications.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxEdit(int id, string comment, int statusID)
        {
            //db.Entry(publisher).State = EntityState.Modified;
            //db.SaveChanges();
            //return Json(publisher);
            Application application = (from x in db.Applications
                                       where x.ApplicationID == id
                                       select x).Single();
            string userID = User.Identity.GetUserId();
            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                if (userID != application.OpenPosition.Location.ManagerID)
                {
                    return Json(false);
                }

            }
            var statusCheck = from x in db.ApplicationStatus1
                              where x.ApplicationStatusID == statusID
                              select x;
            if (statusCheck.Count() == 1)
            {
                application.ApplicationStatusID = statusCheck.Single().ApplicationStatusID;
            }
            application.ManagerNotes = comment;

            db.Entry(application).State = EntityState.Modified;
            db.SaveChanges();

            return Json(true);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxDelete(int id)
        {
            Application application = db.Applications.Find(id);
            string userID = User.Identity.GetUserId();
            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                if (userID != application.OpenPosition.Location.ManagerID)
                {
                    return Json(false);
                }

            }
            db.Applications.Remove(application);
            db.SaveChanges();
            return Json(true);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI/Views/Applications/Delete.cshtml
@model JobBoard.DataLayer.Application

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Application</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ManagerNotes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ManagerNotes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ResumeFileName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ResumeFileName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ApplicationStatu.StatusName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationStatu.StatusName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OpenPosition.OpenPositionID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OpenPosition.OpenPositionID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserDetail.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserDetail.FirstName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Cancel", "Index", null , new { @class="btn btn-primary"})
            </div>
        }
    </div>
</div>

JobBoard.UI/Views/Applications/Details.cshtml
@model JobBoard.DataLayer.Application

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <h2>Details</h2>

    <div>
        <h4>Application</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ManagerNotes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ManagerNotes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ResumeFileName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ResumeFileName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ApplicationStatu.StatusName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationStatu.StatusName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OpenPosition.OpenPositionID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OpenPosition.OpenPositionID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserDetail.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserDetail.FirstName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ApplicationID }, new { @class = "btn btn-primary" }) |
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
    </p>
</div>

JobBoard.UI/Views/Applications/Edit.cshtml
@model JobBoard.DataLayer.Application

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Application</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ApplicationID)
            @Html.HiddenFor(model => model.OpenPositionID)
            @Html.HiddenFor(model => model.UserID)
            @Html.HiddenFor(model => model.ApplicationDate)
            @Html.HiddenFor(model => model.ResumeFileName)


            <div class="form-group">
                Name
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.UserDetail.FirstName) @Html.DisplayFor(model => model.UserDetail.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.ApplicationDate)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ApplicationStatusID, "ApplicationStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ApplicationStatusID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ApplicationStatusID, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    @Html.ActionLink("Cancel", "Index",null,new { @class="btn btn-danger"})
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobBoard.UI/Views/Applications/Index.cshtml
@model IEnumerable<JobBoard.DataLayer.Application>

@{
    /**/

    ViewBag.Title = "Index";
}
@using JobBoard.DataLayer
<div class="container">
    <h2>Index</h2>



    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OpenPosition.Position.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManagerNotes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationStatu.StatusName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResumeFileName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            string idtext = "TableItem" + @Html.DisplayFor(modelItem => item.ApplicationID);
            <tr id="@idtext">
                <td>
                    @Html.DisplayFor(modelItem => item.UserDetail.FirstName) @Html.DisplayFor(modelItem => item.UserDetail.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OpenPosition.Position.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationDate)
                </td>
                <td class="ManagerNotes">
                    @Html.DisplayFor(modelItem => item.ManagerNotes)
                </td>
                <td class="StatusName">
                    @Html.DisplayFor(modelItem => item.ApplicationStatu.StatusName)
                </td>
                <td>
                    <a href="@Html.DisplayFor(modelItem => item.ResumeFileName)">Download Resume</a>

                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.ApplicationID }, new { @class = "btn btn-primary" }) |*@
                    <div class="btn btn-primary AjaxEdit" data-DBID="@Html.DisplayFor(modelItem => item.ApplicationID)">Edit</div> |
                    @Html.ActionLink("Details", "Details", new { id = item.ApplicationID }, new { @class = "btn btn-primary" }) |
                    <div class="btn btn-danger AjaxDelete" data-DBID="@Html.DisplayFor(modelItem => item.ApplicationID)">Delete</div>
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.ApplicationID }, new { @class = "btn btn-danger" })*@
                </td>
            </tr>
        }

    </table>
</div>
<!-- The Modal -->
<div id="EditModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>

        @using (Html.BeginForm("", "", FormMethod.Post, new { id = "EditFourm" }))
        {
            <input id="EditTarget" name="id" type="hidden" value="1" />
            @*@Html.Hidden("id", 1)*@
            @Html.AntiForgeryToken()
            <input id="AjaxEditFourmText" name="comment" type="text">
            <br>
            <select id="StatusNameSelector" name="statusId">
                @using (JobBoardEntities db = new JobBoardEntities())
                {
                    foreach (var item in db.ApplicationStatus1.ToList())
                    {
                        <option value=@item.ApplicationStatusID>@item.StatusName</option>
                    }

                }
            </select>
            <br>
            <input id="AjaxEditFourmSubmit" type="submit" value="Submit">
        }
    </div>

</div>

<style>
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }
</style>

@section Scripts{
    <script>
        $(".AjaxEdit").click(
            function (e) {
                let itemID = $(this).attr("data-DBID");
                let editScreen = $("#EditModal");
                //let hiddenIDfield = editScreen.children("#id");
                //let hiddenIDfield = $("EditTarget");
                let hiddenIDfield =  document.getElementById("EditTarget");
                hiddenIDfield.value = itemID;
                editScreen.show();
            }
        )
        $("#EditFourm").submit(
            function (e) {
                e.preventDefault();
                let EditFourm = $("#EditFourm");
                let toSend = EditFourm.serializeArray();
                console.log(toSend);
                $.ajax({
                    url: "@Url.Action("AjaxEdit","Applications")",
                    type: "POST",
                    data: toSend
                });
                $("#EditModal").hide();
                //$("#AjaxEditFourmText");
                let textForTableRowID = "#TableItem" + toSend[0].value;
                let tableRow = $(textForTableRowID);
                let managerNotes = tableRow.children(".ManagerNotes")[0];
                managerNotes.innerText = toSend[2].value;
                let StatusName = tableRow.children(".StatusName")[0];
                //let StatusNameSelector = $("#StatusNameSelector");
                let StatusNameSelector = document.getElementById("StatusNameSelector");
                //.selectedIndex
                //.value
                StatusName.innerText = StatusNameSelector.options[StatusNameSelector.selectedIndex].innerText;

            }
        )
        $(".AjaxDelete").click(function (e) {
            let itemID = $(this).attr("data-DBID");
            let AntiForgeryToken = '@Html.AntiForgeryToken()';
            let patt = /value="(.+)"/;
            
            AntiForgeryToken=AntiForgeryToken.match(patt, AntiForgeryToken)[1];
            $.ajax({
                url: "@Url.Action("AjaxDelete", "Applications")",
                type: "POST",
                data:  [
                    { name: "id", value: itemID },
                    { name: "__RequestVerificationToken", value: AntiForgeryToken}
                    ]
            });
            let textForTableRowID = "#TableItem" + itemID;
            $(textForTableRowID).remove();
        });
    </script>
}