JobBoard.UI/Controllers/OpenPositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.DataLayer;
using Microsoft.AspNet.Identity;

namespace JobBoard.UI.Controllers
{
    public class OpenPositionsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: OpenPositions
        public ActionResult Index(string categoriesSearch, string titleSearch, string locationSearch, int? categoryID)
        {
            var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);

            if (!string.IsNullOrEmpty(categoriesSearch))
            {
                openPositions = openPositions.Where(x=>x.Position.Category.CategoryName.Contains(categoriesSearch));
            }
            if (!string.IsNullOrEmpty(titleSearch))
            {
                openPositions = openPositions.Where(x=>x.Position.Title.Contains(titleSearch));
            }
            if (!string.IsNullOrEmpty(locationSearch))
            {
                openPositions = openPositions.Where(x => x.Location.LocationName.Contains(locationSearch));
            }
            if (categoryID!=null)
            {
                openPositions = openPositions.Where(x=>x.Position.CategoryID== categoryID);
            }
            return View(openPositions.ToList());
        }

        // GET: OpenPositions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // GET: OpenPositions/Create
        [Authorize(Roles = "Admin, Managers")]
        public ActionResult Create()
        {
            string userID = User.Identity.GetUserId();
            var locations = db.Locations.Where(x=>true);

            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                locations = locations.Where(x=>x.ManagerID==userID);

            }
            if (locations.Count()==0)
            {
                return RedirectToAction("ErrorNotAManager");
            }
            ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title");
            return View();
        }

        // POST: OpenPositions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Managers")]
        public ActionResult Create([Bind(Include = "OpenPositionID,PositionID,LocationID")] OpenPosition openPosition)
        {
            string userID = User.Identity.GetUserId();
            var locations = db.Locations.Where(x => true);

            if (!User.IsInRole("Admin"))
            {
                // the user is not an admin
                locations = locations.Where(x => x.ManagerID == userID);

            }
            if (locations.Count() == 0)
            {
                return RedirectToAction("ErrorNotAManager");
            }
            var locationCheck = from x in locations
                                where x.LocationID == openPosition.LocationID
                                select x;
            if (locationCheck.Count()==0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            if (ModelState.IsValid)
            {
                db.OpenPositions.Add(openPosition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName", openPosition.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPosition.PositionID);
            return View(openPosition);
        }


        // GET: OpenPositions/Delete/5
        [Authorize(Roles = "Admin, Managers")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            if (openPosition.Location.ManagerID!= User.Identity.GetUserId()&&!User.IsInRole("Admin"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(openPosition);
        }

        // POST: OpenPositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Managers")]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition.Location.ManagerID != User.Identity.GetUserId() && !User.IsInRole("Admin"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            db.OpenPositions.Remove(openPosition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Apply(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            string userID = User.Identity.GetUserId();
            var applicationCheck = from x in db.Applications
                                   where x.UserID == userID && x.OpenPositionID == openPosition.OpenPositionID
                                   select x;
            if (applicationCheck.Count()==0)
            {
                Application application = new Application();
                application.ApplicationDate = DateTime.Now;
                application.ApplicationStatusID = 1;
                application.ResumeFileName = (from x in db.UserDetails
                                              where x.UserID == userID
                                              select x.ResumeFileName).Single();
                application.UserID = userID;
                application.OpenPositionID = openPosition.OpenPositionID;
                db.Applications.Add(application);
                db.SaveChanges();
                ViewBag.Message = "You have successfully applied";
            }
            else
            {
                ViewBag.Message = "You have already applied";
            }
            
            return View();
        }
        public ActionResult ErrorNotAManager()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI/Views/OpenPositions/Apply.cshtml
@{
    ViewBag.Title = "Apply";
}

<h2>Apply</h2>

<p>@ViewBag.Message</p>

JobBoard.UI/Views/OpenPositions/Create.cshtml
@model JobBoard.DataLayer.OpenPosition

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OpenPosition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PositionID, "PositionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobBoard.UI/Views/OpenPositions/Delete.cshtml
@model JobBoard.DataLayer.OpenPosition

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OpenPosition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.ManagerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.ManagerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JobBoard.UI/Views/OpenPositions/Details.cshtml
@model JobBoard.DataLayer.OpenPosition

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OpenPosition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.ManagerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.ManagerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OpenPositionID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JobBoard.UI/Views/OpenPositions/ErrorNotAManager.cshtml
@{
    ViewBag.Title = "Error Not A Manager";
}

<h2>@ViewBag.Title</h2>

We are Sorry you need to be a Manager of a least one location to create a Postion.

JobBoard.UI/Views/OpenPositions/Index.cshtml
@model IEnumerable<JobBoard.DataLayer.OpenPosition>

@{
    ViewBag.Title = "Index";
}
@using JobBoard.DataLayer


<div class="container">

    <div class="col-md-12 tab-wrap">

        <div class="tab-content p-4" id="v-pills-tabContent">

            <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
                @* job search fourm is here *@
                <form action="/OpenPositions" class="search-job">
                    <div class="row no-gutters">
                        <div class="col-md mr-md-2">
                            <div class="form-group">
                                <div class="form-field">
                                    <div class="icon"><span class="icon-briefcase"></span></div>
                                    <input name="titleSearch" type="text" class="form-control" placeholder="Job title">
                                </div>
                            </div>
                        </div>
                        <div class="col-md mr-md-2">
                            <div class="form-group">
                                <div class="form-field">
                                    @*TODO Bruce Smith fix icon *@
                                    <div class="icon"><i class="fas fa-archive"></i></div>
                                    <input name="categoriesSearch" type="text" class="form-control" placeholder="Category">
                                </div>
                            </div>
                        </div>
                        <div class="col-md mr-md-2">
                            <div class="form-group">
                                <div class="form-field">
                                    <div class="icon"><span class="icon-map-marker"></span></div>
                                    <input name="locationSearch" type="text" class="form-control" placeholder="Location">
                                </div>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <div class="form-field">
                                    <button type="submit" class="form-control btn btn-primary">Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        @{


            foreach (OpenPosition job in Model)
            {

                <div class="col-md-12 ftco-animate">
                    <div class="job-post-item p-4 d-block d-lg-flex align-items-center">
                        <div class="one-third mb-4 mb-md-0">
                            <div class="job-post-item-header align-items-center">
                                <span class="subadge">@job.Position.Category.CategoryName</span>
                                <h2 class="mr-3 text-black"><a href="#">@job.Position.Title</a></h2>
                            </div>
                            <div class="job-post-item-body d-block d-md-flex">
                                <div class="mr-3"><span class="icon-layers"></span> <a href="#">@job.Location.UserDetail.FirstName @job.Location.UserDetail.LastName</a></div>
                                <div><span class="icon-my_location"></span> <span>@job.Location.Address</span></div>
                            </div>
                        </div>

                        <div class="one-forth ml-auto d-flex align-items-center mt-4 md-md-0">
                            @*<div>
                                    <a href="#" class="icon text-center d-flex justify-content-center align-items-center icon mr-2">
                                        <span class="icon-heart"></span>
                                    </a>
                                </div>*@
                            <a href="@Url.Action("Apply","OpenPositions")/@job.OpenPositionID" class="btn btn-primary py-2">Apply Job</a>
                        </div>
                    </div>
                </div><!-- end -->
            }
        }


    </div>
</div>