JobBoard.UI/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.DataLayer;

namespace JobBoard.UI.Controllers
{
    public class CategoriesController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CategoryID,CategoryDescription,CategoryName")] Category category, HttpPostedFileBase IconFile)
        {
            if (ModelState.IsValid)
            {
                if (IconFile != null)
                {
                    category.IconFileName = FileUpload.UploadImageFile(IconFile, Server, "/Content/Uploaded/img/");
                }
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryDescription,CategoryName")] Category category, HttpPostedFileBase IconFile)
        {
            if (ModelState.IsValid)
            {
                if (IconFile != null)
                {
                    category.IconFileName = FileUpload.UploadImageFile(IconFile, Server, "/Content/Uploaded/img/");
                }
                else
                {
                    string oldFileName = (from x in db.Categories
                                          where x.CategoryID == category.CategoryID
                                          select x.IconFileName).Single();
                    category.IconFileName = oldFileName;
                }
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CardView()
        {
            return View(db.Categories.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.DataLayer;

namespace JobBoard.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LocationsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Locations
        public ActionResult Index()
        {
            var locations = db.Locations.Include(l => l.UserDetail);
            return View(locations.ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            var managers = from x in db.AspNetUsers
                           where x.AspNetRoles.Where(y => y.Name == "Managers").Count() > 0
                           select x;

            ViewBag.Managers = managers.ToList();
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationName,ManagerID,Latitude,Longitude,Address")] Location location, HttpPostedFileBase PhotoFile)
        {
            if (ModelState.IsValid)
            {
                if (PhotoFile != null)
                {
                    location.PhotoFileName = FileUpload.UploadImageFile(PhotoFile, Server, "/Content/Uploaded/img/");
                }
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var managers = from x in db.AspNetUsers
                           where x.AspNetRoles.Where(y => y.Name == "Managers").Count() > 0
                           select x;

            ViewBag.Managers = managers.ToList();

            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            var managers = from x in db.AspNetUsers
                           where x.AspNetRoles.Where(y => y.Name == "Managers").Count() > 0
                           select x;
            ViewBag.Managers = managers.ToList();
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationName,LocationID,ManagerID,Latitude,Longitude,Address")] Location location, HttpPostedFileBase PhotoFile)
        {
            if (ModelState.IsValid)
            {
                if (PhotoFile != null)
                {
                    location.PhotoFileName = FileUpload.UploadImageFile(PhotoFile, Server, "/Content/Uploaded/img/");
                }
                else
                {
                    string oldFileName = (from x in db.Locations
                                          where x.LocationID == location.LocationID
                                          select x.PhotoFileName).Single();
                    location.PhotoFileName = oldFileName;
                }
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var managers = from x in db.AspNetUsers
                           where x.AspNetRoles.Where(y => y.Name == "Managers").Count() > 0
                           select x;
            ViewBag.Managers = managers.ToList();
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.DataLayer;

namespace JobBoard.UI.Controllers
{
    [Authorize(Roles = "Admin, Managers")]
    public class PositionsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Positions
        public ActionResult Index()
        {
            var positions = db.Positions.Include(p => p.Category);
            return View(positions.ToList());
        }

        // GET: Positions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PositionID,Title,JobDescription,CategoryID,PhotoFileName")] Position position, HttpPostedFileBase PhotoFile)
        {
            if (ModelState.IsValid)
            {
                if (PhotoFile!= null)
                {
                    position.PhotoFileName= FileUpload.UploadImageFile(PhotoFile, Server,"/Content/Uploaded/img/");
                }
                db.Positions.Add(position);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", position.CategoryID);
            return View(position);
        }

        // GET: Positions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", position.CategoryID);
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PositionID,Title,JobDescription,CategoryID,PhotoFileName")] Position position, HttpPostedFileBase PhotoFile)
        {
            if (ModelState.IsValid)
            {
                if (PhotoFile != null)
                {
                    position.PhotoFileName = FileUpload.UploadImageFile(PhotoFile, Server, "/Content/Uploaded/img/");
                }
                else
                {
                    string oldFileName = (from x in db.Positions
                                          where x.PositionID == position.PositionID
                                          select x.PhotoFileName).Single();
                    position.PhotoFileName = oldFileName;
                }
                db.Entry(position).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", position.CategoryID);
            return View(position);
        }

        // GET: Positions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Positions.Find(id);
            db.Positions.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI/Views/Shared/Old_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

JobBoard.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Skillhunt - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/Content/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/Content/css/animate.css">

    <link rel="stylesheet" href="/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/Content/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/Content/css/magnific-popup.css">
    <link rel="stylesheet" href="/Content/css/aos.css">
    <link rel="stylesheet" href="/Content/css/ionicons.min.css">
    <link rel="stylesheet" href="/Content/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/Content/css/jquery.timepicker.css">

    <link rel="stylesheet" href="/Content/css/flaticon.css">
    <link rel="stylesheet" href="/Content/css/icomoon.css">
    <link rel="stylesheet" href="/Content/css/style.css">

    <link rel="stylesheet" href="/Content/css/superfish.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container-fluid px-md-4	">
            <a class="navbar-brand" href="@Url.Action("Index","Home")">Skillhunt</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>
            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto sf-menu">
                    <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","OpenPositions")" class="nav-link">Browse Jobs</a></li>
                    <li class="nav-item"><a href="@Url.Action("CardView","Categories")" class="nav-link">Categories</a></li>
                    <li class="nav-item"><a href="@Url.Action("Contact","Home")" class="nav-link">Contact</a></li>
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("Managers") || User.IsInRole("Admin"))
                        {
                            <li class="menu-has-children nav-item">
                                <a class="nav-link" href="">Manager</a>
                                <ul class="submenu">
                                    <li class="nav-item"><a href="@Url.Action("Index", "Positions")" class="nav-link">Manage  Positions </a></li>
                                    <li class="nav-item"><a href="@Url.Action("Index", "Applications")" class="nav-link">Manage Applications</a></li>
                                    <li class="nav-item"><a href="@Url.Action("Create", "OpenPositions")" class="nav-link">List New Job </a></li>
                                </ul>
                            </li>
                        }
                        if (User.IsInRole("Admin"))
                        {
                            <li class="menu-has-children nav-item">
                                <a class="nav-link" href="">Admin</a>
                                <ul class="submenu">
                                    <li class="nav-item"><a href="@Url.Action("Index", "UsersAdmin")" class="nav-link">Manage Users</a></li>
                                    <li class="nav-item"><a href="@Url.Action("Index", "RolesAdmin")" class="nav-link">Manage Roles</a></li>
                                    <li class="nav-item"><a href="@Url.Action("Index", "Locations")" class="nav-link">Manage Locations</a></li>
                                    <li class="nav-item"><a href="@Url.Action("Index", "UserDetailsAdmin")" class="nav-link">Manage User Information</a></li>
                                    <li class="nav-item"><a href="@Url.Action("Index", "Categories")" class="nav-link">Manage categories</a></li>
                                </ul>
                            </li>
                        }
                    }
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->
    @if (ViewBag.displayHeader == null)
    {
        <div class="hero-wrap hero-wrap-2" style="background-image: url(&quot;Content/images/bg_1.jpg&quot;); background-position: 50% 0px;" data-stellar-background-ratio="0.5">
            <div class="overlay"></div>
            <div class="container">
                <div class="row no-gutters slider-text align-items-end justify-content-start">
                    <div class="col-md-12 ftco-animate text-center mb-5 fadeInUp ftco-animated">
                        <p class="breadcrumbs mb-0"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Canditates</span></p>
                        <h1 class="mb-3 bread">Hire Your Best Candidates</h1>
                    </div>
                </div>
            </div>
        </div>
    }
    <!--Content-->
    <div id="Content">
        @RenderBody()
    </div>
    <!--End Content-->
    <footer class="ftco-footer ftco-bg-dark ftco-section">
        <div class="container">
            @*<div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Skillhunt Jobboard</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Employers</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="pb-1 d-block">Browse Candidates</a></li>
                            <li><a href="#" class="pb-1 d-block">Post a Job</a></li>
                            <li><a href="#" class="pb-1 d-block">Employer Listing</a></li>
                            <li><a href="#" class="pb-1 d-block">Resume Page</a></li>
                            <li><a href="#" class="pb-1 d-block">Dashboard</a></li>
                            <li><a href="#" class="pb-1 d-block">Job Packages</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-4">
                        <h2 class="ftco-heading-2">Candidate</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="pb-1 d-block">Browse Jobs</a></li>
                            <li><a href="#" class="pb-1 d-block">Submit Resume</a></li>
                            <li><a href="#" class="pb-1 d-block">Dashboard</a></li>
                            <li><a href="#" class="pb-1 d-block">Browse Categories</a></li>
                            <li><a href="#" class="pb-1 d-block">My Bookmarks</a></li>
                            <li><a href="#" class="pb-1 d-block">Candidate Listing</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-4">
                        <h2 class="ftco-heading-2">Account</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="pb-1 d-block">My Account</a></li>
                            <li><a href="#" class="pb-1 d-block">Sign In</a></li>
                            <li><a href="#" class="pb-1 d-block">Create Account</a></li>
                            <li><a href="#" class="pb-1 d-block">Checkout</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>*@
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>


    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    <script src="/Content/js/jquery.min.js"></script>
    <script src="/Content/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="/Content/js/popper.min.js"></script>
    <script src="/Content/js/bootstrap.min.js"></script>
    <script src="/Content/js/jquery.easing.1.3.js"></script>
    <script src="/Content/js/jquery.waypoints.min.js"></script>
    <script src="/Content/js/jquery.stellar.min.js"></script>
    <script src="/Content/js/owl.carousel.min.js"></script>
    <script src="/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="/Content/js/aos.js"></script>
    <script src="/Content/js/jquery.animateNumber.min.js"></script>
    <script src="/Content/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="/Content/js/google-map.js"></script>
    <script src="~/Content/js/hoverIntent.js"></script>
    <script src="/Content/js/superfish.js"></script>
    <script src="/Content/js/main.js"></script>
    <script>
        jQuery(document).ready(function () {
            jQuery('ul.sf-menu').superfish();
        });
    </script>
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/5dea9071d96992700fcb205a/default';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
    @RenderSection("Scripts", false)
</body>
</html>